### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by afonsopereiraaa** [UntitledEntity/P2C-Client#3]
hi! so im getting this errors while compiling the p2c-client.

![image](https://user-images.githubusercontent.com/106179759/197339457-64534349-f17b-47eb-b658-a0e50a468373.png)
![image](https://user-images.githubusercontent.com/106179759/197339462-b2efa6a3-78c2-48e6-8213-07bde5e6f478.png)

Error translation:

C3848 | expression having type 't std::uniform_int_distribution<unsigned int>' would miss some qualified Error const-volatile in order to call 'unsigned int std::uniform_int<_Ty>::operator()<std::default_random_engine>(_Engine & )' csgo-loader C:\Users\Afonso Pereira\Downloads\P2C-Client-main\Utils\Utils.hpp 16

**Comment by afonsopereiraaa** [comment]
![image](https://user-images.githubusercontent.com/106179759/197340198-1025bf70-3f06-4d9f-90bd-1bf726881303.png)

**Comment by UntitledEntity** [comment]
Are you on the correct std:c++ version?

Assure that the underlined version is the one you have selected.
![isssuefix](https://user-images.githubusercontent.com/75293608/197341814-0098b61b-a017-4e25-996c-5f8219fcabb7.png)
